* fix config.url startswith slash
hexojs/hexo-util pull request #188
Opened 2020-03-20 04:34 UTC by UMU618

If I use '//blog.umu618.com' as config.url, the url_for is malfunctioned.

2020-03-20 10:12 UTC, SukkaW commented on lib/full_url_for.js
> +    const config_url = config.url.startsWith('//') ? `https:${config.url}` : config.url;
Why `//` prefixed URL will be considered as `https` supported?

2020-04-22 15:07 UTC, UMU618 commented
> I can't see the point of the PR.
> 
> If you are going to address a fix, then add your test cases then.

if you use HTTP and HTTPS together, you may set config.url as //your-domain.

2020-04-25 05:23 UTC, curbengh commented
> if you use HTTP and HTTPS together

May I know your specific use cases of `config.url`? For default use case, it's mainly for SEO purpose ([open_graph.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js)). SEO typically requires a canonical link, either HTTP or HTTPS, not both.

For linking other pages in your blog, you should use relative link, e.g. `/2018/03/20/foo-bar/`, homepage is just `/`.

2020-04-26 16:37 UTC, UMU618 commented
> > if you use HTTP and HTTPS together
> 
> May I know your specific use cases of `config.url`? For default use case, it's mainly for SEO purpose ([open_graph.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js)). SEO typically requires a canonical link, either HTTP or HTTPS, not both.
> 
> For linking other pages in your blog, you should use relative link, e.g. `/2018/03/20/foo-bar/`, homepage is just `/`.

## * fix config.url startswith slash #188
## https://github.com/hexojs/hexo-util/pull/188
url: //blog.umu618.com

2020-04-26 16:38 UTC, UMU618 commented
> > if you use HTTP and HTTPS together
> 
> May I know your specific use cases of `config.url`? For default use case, it's mainly for SEO purpose ([open_graph.js](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js)). SEO typically requires a canonical link, either HTTP or HTTPS, not both.
> 
> For linking other pages in your blog, you should use relative link, e.g. `/2018/03/20/foo-bar/`, homepage is just `/`.

https://github.com/UMU618/blog/blob/master/_config.yml

2021-03-31 01:10 UTC, stevenjoezhang requested changes
It is recommended to redirect http to https with status code 301

2021-03-31 06:14 UTC, UMU618 commented
> It is recommended to redirect http to https with status code 301

Agree. but not all free hosts support https.

2021-03-31 09:50 UTC, UMU618 commented
> If https is not supported, the URL should be `http://your-domain`, instead of `//your-domain` in Hexo `_config.yml`

Maintaining two copies of config is inconvenient, so I modify the code.

2021-03-31 16:42 UTC, UMU618 commented
> I don't understand why it's necessary maintaining two copies of config.
> 
> * If your site supports HTTPS: `url: https://your-domain`
> * If your site does not support HTTPS: `url: http://your-domain`
> * If your site supports both HTTP and HTTPS: `url: https://your-domain` and set 301 redirect
> 
> In all these cases, one config file is enough.

What about having 2 hosts, one supports HTTPS, another not?

2021-03-31 16:47 UTC, stevenjoezhang commented
If you have two hosts serving the same content, I would suggest a 301 redirect for better SEO.

2021-03-31 16:50 UTC, stevenjoezhang commented
Besides, even if you have successfully set '//blog.umu618.com' as config.url, you still can not deploy it to another host. Your Pull Request does not resolve the issue.

2021-04-01 03:03 UTC, UMU618 commented
> If you have two hosts serving the same content, I would suggest a 301 redirect for better SEO.

Thank you. People that can access host A, can NOT access host B.

2021-04-01 03:05 UTC, UMU618 commented
> Besides, even if you have successfully set '//blog.umu618.com' as config.url, you still can not deploy it to another host. Your Pull Request does not resolve the issue.

deploy to another host via `scp`

2021-04-01 04:16 UTC, jiangtj commented
> People that can access host A, can NOT access host B.

Maybe consider overriding configuration parameters via the command line. For example, to implement the following command line.

```
hexo g --config.url=http(s)://another.host
```

Currently, Hexo supports custom configuration file paths

![image](https://user-images.githubusercontent.com/15902347/113242544-ced18080-92e3-11eb-998e-785a9ce4e17e.png)

2021-04-29 18:13 UTC, closed without merging

2022-02-13 13:49 UTC, UMU618 commented
这个 PR 很显然是有用的，您在本地测试的时候一般就用 http，上传到服务器上就用 https，这就是典型的两处环境不一样，都兼容不是更好的？

2022-02-13 15:47 UTC, stevenjoezhang commented
你所说的这个情况本来就支持。设置 `url: https://your-domain` 就可以实现你说的

> 在本地测试的时候一般就用 http，上传到服务器上就用 https

本地测试打开 `http://localhost:4000`，上传服务器就用 `https://your-domain`，没有任何问题。

2022-02-15 07:05 UTC, UMU618 commented
> 你所说的这个情况本来就支持。设置 `url: https://your-domain` 就可以实现你说的

我的本地使用的一毛一样的域名，设置 hosts 的，不是 localhost，因为我有两个网站，一个不支持 https。

2022-02-15 11:58 UTC, stevenjoezhang commented
所以你的根本需求还是：有两个域名，一个支持 https，一个不支持，它们需要部署同一个 Hexo 博客。是这样么？
不然本地测试并不需要设置 hosts，这样反而麻烦了。

2022-02-15 14:18 UTC, UMU618 commented
> 所以你的根本需求还是：有两个域名，一个支持 https，一个不支持，它们需要部署同一个 Hexo 博客。是这样么？
> 不然本地测试并不需要设置 hosts，这样反而麻烦了。

是这样的，前面用英文讲过，被忽视，所以只能大家能遇到的举个例子。

2022-02-15 14:35 UTC, stevenjoezhang commented
我觉得没有被忽视，我已经给出过建议

<img width="1434" alt="截屏2022-02-15 下午10 34 18" src="https://user-images.githubusercontent.com/16272760/154083168-4c3a72bb-84d1-43b3-87e6-0a1d8d5b404f.png">

所以这个不支持 https 的域名是你只在本地测试时使用，还是可以通过公网访问？

2022-02-15 14:40 UTC, UMU618 commented
您可以理解为 CDN 的贫穷版……自然是要公网访问，域名可以对不同运营商解析不同 IP，这也可能导致页面放在多个 host 上。